#Starter Configuration File
project_name: 'rpi-data'        #Set your package
package_index: 'https://raw.githubusercontent.com/CarmeLabs/packages/master/default/config/index.yaml' #set to local for config/index.yaml
container_url: 'registry.hub.docker.com' #Location for storing/retreiving containerss
merge_list: ['./.carmeignore', './docker-compose.yaml', 'config/carme-config.yaml']
host: localhost
